import React from 'react'
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

export default function SliderBar() {
    
    const sliderSettings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false, 
  };

    return (
        <>
            <section className="vs-hero-wrapper mt-5 ">
                <div className="vs-hero-carousel" data-slidertype="responsive" data-globalbgcolor="#2DA0A4">

                    <Slider {...sliderSettings}>
                    <div className="ls-slide">
                        <img width="1920" height="295" src="assets/img/hero/h-s-2-2.png" className="ls-l ls-img-layer" alt="bg" decoding="async" style={{ fontSize: '36px', color: '#000', stroke: '#000', strokeWidth: '0px', textAlign: 'left', fontStyle: 'normal', textDecoration: 'none', textTransform: 'none', fontWeight: '400', letterSpacing: '0px', backgroundPosition: '0% 0%', backgroundRepeat: 'no-repeat', backgroundClip: 'border-box', overflow: 'visible', top: '775px', left: '-10px', WebkitBackgroundClip: 'border-box' }} 
                        data-ls="static:forever;" />
                        <img width="708" height="710" src="assets/img/hero/hero-2-1.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" />
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" decoding="async" 
                        style={{ fontSize: '36px', color: '#000', stroke: '#000', strokeWidth: '0px', textAlign: 'left', fontStyle: 'normal', textDecoration: 'none', textTransform: 'none', fontWeight: '400', letterSpacing: '0px', backgroundPosition: '0% 0%', backgroundRepeat: 'no-repeat', backgroundClip: 'border-box', overflow: 'visible', top: '170px', left: '1171px', WebkitBackgroundClip: 'border-box' }} 
                        data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                        <h1 style={{ fontSize: '70px', stroke: '#000', strokeWidth: '0px', textAlign: 'left', fontStyle: 'normal', textDecoration: 'none', textTransform: 'none', letterSpacing: '0px', backgroundPosition: '0% 0%', backgroundRepeat: 'no-repeat', backgroundClip: 'border-box', overflow: 'visible', color: '#ffffff', fontFamily: "'Fredoka', sans-serif", lineHeight: '70px', fontWeight: '600', left: '310px', top: '305px', WebkitBackgroundClip: 'border-box' }} 
                        className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            World Best
                        </h1>
                        <h1 style={{fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '374px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Children Care
                        </h1>
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '445px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Program
                        </h1>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '315px',
                            top: '535px',
                            WebkitBackgroundClip: 'border-box'
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">Montessori classNamerooms and materials encourage</p>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '315px',
                            top: '573px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">curiosity and discovery.</p>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '315px',
                            top: '642px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '149px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            World Best
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '245px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Children Care
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '351px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Program
                        </h1>
                        <p style={{
                            fontSize: '34px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '150px',
                            top: '477px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">Montessori classNamerooms and materials encourage</p>
                        <p style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '150px',
                            top: '538px',
                            fontSize: '34px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">curiosity and discovery.</p>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '150px',
                            top: '630px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '90px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            World Best
                        </h1>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '236px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Children Care
                        </h1>
                        <h1 style={{
                            fontSize: '110px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '380px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Program
                        </h1>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '100px',
                            top: '578px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <img width="708" height="710" src="assets/img/hero/hero-2-1.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '47px',
                            left: '1003px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:4; parallaxevent:cursor;" />
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '76px',
                            left: '1340px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                    </div>
                    </Slider>

                    <Slider {...sliderSettings}>
                    <div className="ls-slide" data-ls="duration:12000; transition2d:5; kenburnsscale:1.2;">
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '28px',
                            left: '1088px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                        <img width="715" height="711" src="assets/img/hero/hero-2-2.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '28px',
                            left: '800px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:4; parallaxevent:cursor;" />
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '305px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Dive Into The
                        </h1>
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '374px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Greatness of Kid
                        </h1>
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '445px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Learning
                        </h1>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '315px',
                            top: '535px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">Montessori classNamerooms and materials encourage</p>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '315px',
                            top: '573px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">curiosity and discovery.</p>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '315px',
                            top: '642px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '149px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Dive Into The
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '245px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Greatness of Kid
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '90px',
                            fontWeight: '600',
                            left: '150px',
                            top: '351px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Learning
                        </h1>
                        <p style={{
                            fontSize: '34px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: 'Jost, sans-serif',
                            color: '#ffffff',
                            left: '150px',
                            top: '477px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">Montessori classNamerooms and materials encourage</p>
                        <p style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '150px',
                            top: '630px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">curiosity and discovery.</p>
                        <div style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '90px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '90px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Dive Into The
                        </h1>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '236px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Greatness of Kid
                        </h1>
                        <h1 style={{
                            fontSize: '110px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '110px',
                            fontWeight: '600',
                            left: '100px',
                            top: '380px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Learning
                        </h1>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '100px',
                            top: '578px',
                            fontFamily: 'Fredoka, sans-serif',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '29px',
                            left: '1183px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                        <img width="715" height="711" src="assets/img/hero/hero-2-2.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '-19px',
                            left: '917px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:4; parallaxevent:cursor;" />
                    </div>
                    </Slider>

                    <Slider {...sliderSettings}>
                    <div className="ls-slide" data-ls="duration:12000; transition2d:5; kenburnsscale:1.2;">
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '305px',
                            left: '697px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                        <img width="710" height="711" src="assets/img/hero/hero-2-3.png" className="ls-l ls-hide-phone ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: '400',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '118px',
                            left: '782px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:4; parallaxevent:cursor;" />
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '305px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Modern Kid's
                        </h1>
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: 'Fredoka, sans-serif',
                            lineHeight: '70px',
                            fontWeight: '600',
                            left: '310px',
                            top: '374px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Equibment For
                        </h1>
                        <h1 style={{
                            fontSize: '70px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '70px',
                            fontWeight: 600,
                            left: '310px',
                            top: '445px',
                            WebkitBackgroundClip: 'border-box',
                        }}
                            classNameName="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Better Study
                        </h1>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: "'Jost', sans-serif",
                            color: '#ffffff',
                            left: '315px',
                            top: '535px',
                            WebkitBackgroundClip: 'border-box',
                        }}
                            classNameName="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">
                            Montessori classNamerooms and materials encourage
                        </p>
                        <p style={{
                            fontSize: '24px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: "'Jost', sans-serif",
                            color: '#ffffff',
                            left: '315px',
                            top: '573px',
                            WebkitBackgroundClip: 'border-box',
                        }}
                            classNameName="ls-l ls-hide-tablet ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">
                            curiosity and discovery.
                        </p>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: "'Fredoka', sans-serif",
                            WebkitBackgroundClip: 'border-box',
                            left: '315px',
                            top: '642px',
                        }}
                            classNameName="ls-l ls-hide-tablet ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;">
                            <a href="contact.html" classNameName="vs-btn">Start Learning Today</a>
                        </div>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '90px',
                            fontWeight: 600,
                            left: '150px',
                            top: '149px',
                            WebkitBackgroundClip: 'border-box',
                        }}
                            classNameName="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Modern Kid's
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '90px',
                            fontWeight: 600,
                            left: '150px',
                            top: '245px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Equibment For
                        </h1>
                        <h1 style={{
                            fontSize: '90px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '90px',
                            fontWeight: 600,
                            left: '150px',
                            top: '351px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Better Study
                        </h1>
                        <p style={{
                            fontSize: '34px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: "'Jost', sans-serif",
                            color: '#ffffff',
                            left: '150px',
                            top: '477px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:800; easingin:easeOutQuint;">Montessori classNamerooms and materials encourage</p>
                        <p style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            fontFamily: "'Jost', sans-serif",
                            color: '#ffffff',
                            left: '150px',
                            top: '538px',
                            fontSize: '34px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-text-layer" data-ls="offsetxin:-100; delayin:900; easingin:easeOutQuint;">curiosity and discovery.</p>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '150px',
                            top: '630px',
                            fontFamily: "'Fredoka', sans-serif",
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-phone ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '110px',
                            fontWeight: 600,
                            left: '100px',
                            top: '236px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; easingin:easeOutQuint;">
                            Modern Kid's
                        </h1>
                        <h1 style={{
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '110px',
                            fontWeight: 600,
                            left: '100px',
                            top: '236px',
                            fontSize: '110px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:300; easingin:easeOutQuint;">
                            Equibment For
                        </h1>
                        <h1 style={{
                            fontSize: '110px',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            color: '#ffffff',
                            fontFamily: "'Fredoka', sans-serif",
                            lineHeight: '110px',
                            fontWeight: 600,
                            left: '100px',
                            top: '380px',
                            WebkitBackgroundClip: 'border-box',
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-text-layer" data-ls="offsetxin:-100; delayin:600; easingin:easeOutQuint;">
                            Better Study
                        </h1>
                        <div style={{
                            fontSize: '30px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            left: '100px',
                            top: '578px',
                            fontFamily: "'Fredoka', sans-serif",
                            WebkitBackgroundClip: 'border-box'
                        }} className="ls-l ls-hide-desktop ls-hide-tablet ls-html-layer" data-ls="offsetyin:100; delayin:1000; easingin:easeOutQuint; offsetyout:100; easingout:easeOutQuint;"><a href="contact.html" className="vs-btn">Start Learning Today</a></div>
                        <img width="710" height="711" src="assets/img/hero/hero-2-3.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '29px',
                            left: '848px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:4; parallaxevent:cursor;" />
                        <img width="552" height="616" src="assets/img/hero/h-s-2-1.png" className="ls-l ls-hide-desktop ls-hide-tablet ls-img-layer" alt="bg" decoding="async" style={{
                            fontSize: '36px',
                            color: '#000',
                            stroke: '#000',
                            strokeWidth: '0px',
                            textAlign: 'left',
                            fontStyle: 'normal',
                            textDecoration: 'none',
                            textTransform: 'none',
                            fontWeight: 400,
                            letterSpacing: '0px',
                            backgroundPosition: '0% 0%',
                            backgroundRepeat: 'no-repeat',
                            backgroundClip: 'border-box',
                            overflow: 'visible',
                            top: '29px',
                            left: '848px',
                            WebkitBackgroundClip: 'border-box',
                        }} data-ls="parallax:true; parallaxlevel:3; parallaxevent:cursor;" />
                    </div>
                    </Slider>
                    
                </div>
            </section>
        </>
    )
}
